-- Curated public discovery records. All URLs point to official government portals.
-- This extends the existing public.schemes table; it does not create a second catalog.
insert into public.schemes (
  id, name, scheme_type, description, ministry, category, level, state, benefits,
  eligibility, documents_required, application_url, status, last_verified_at, source_url
) values
('00000000-0000-0000-0000-000000000002', 'Pradhan Mantri Awas Yojana – Urban', 'Central Government', 'A Government of India housing mission supporting eligible urban households through its notified housing assistance components.', 'Ministry of Housing and Urban Affairs', 'Housing', 'Central', null, array['Housing assistance according to the applicable PMAY-U component'], array['Eligibility depends on the applicable mission component and official verification', 'Urban household conditions apply'], array['Identity and address documents as required by the implementing authority'], 'https://pmay-urban.gov.in/', 'current', now(), 'https://pmay-urban.gov.in/'),
('00000000-0000-0000-0000-000000000003', 'Ayushman Bharat – Pradhan Mantri Jan Arogya Yojana', 'Central Government', 'A Government of India health assurance scheme for eligible families identified under the scheme framework.', 'Ministry of Health and Family Welfare', 'Healthcare', 'Central', null, array['Health cover according to the notified scheme package and eligibility'], array['Eligibility is determined through the official beneficiary identification process'], array['Documents requested by the official beneficiary or empanelled hospital process'], 'https://pmjay.gov.in/', 'current', now(), 'https://pmjay.gov.in/'),
('00000000-0000-0000-0000-000000000004', 'PM SVANidhi', 'Central Government', 'A central scheme supporting street vendors with access to working-capital credit and related incentives under the official guidelines.', 'Ministry of Housing and Urban Affairs', 'Employment', 'Central', null, array['Working-capital credit support and incentives according to official guidelines'], array['Urban street vendor eligibility and verification requirements apply'], array['Vendor certificate or survey details and documents requested by the lending or implementing channel'], 'https://pmsvanidhi.mohua.gov.in/', 'current', now(), 'https://pmsvanidhi.mohua.gov.in/'),
('00000000-0000-0000-0000-000000000005', 'PM Vishwakarma', 'Central Government', 'A central sector scheme providing end-to-end support to artisans and craftspeople working with their hands and tools in notified trades.', 'Ministry of Micro, Small & Medium Enterprises', 'Skill Development', 'Central', null, array['Skill training', 'Toolkit incentive', 'Credit support', 'Digital transaction and marketing support according to scheme rules'], array['Artisan or craftsperson in one of the notified trades', 'Official registration and verification requirements apply'], array['Identity, occupation and verification documents requested through the official process'], 'https://pmvishwakarma.gov.in/', 'current', now(), 'https://pmvishwakarma.gov.in/'),
('00000000-0000-0000-0000-000000000006', 'Prime Minister’s Employment Generation Programme', 'Central Government', 'A credit-linked subsidy programme supporting eligible new micro-enterprises in rural and urban areas.', 'Ministry of Micro, Small & Medium Enterprises', 'Entrepreneurship', 'Central', null, array['Margin-money subsidy and credit-linked support according to official project and category rules'], array['Individual applicant above 18 years for eligible new projects', 'Education and project conditions apply for specified project costs'], array['Project report, identity, bank and category documents as applicable'], 'https://pmegp.msme.gov.in/Home/Index', 'current', now(), 'https://pmegp.msme.gov.in/Home/Index'),
('00000000-0000-0000-0000-000000000007', 'National Scholarship Portal', 'Central Government', 'The Government of India portal for discovery and application of scholarships published by participating ministries, departments and agencies.', 'Government of India – participating ministries and departments', 'Education', 'Central', null, array['Scholarship support according to the individual scholarship guidelines'], array['Criteria vary by scholarship, including education, institution, category and income where applicable'], array['Documents specified by the selected scholarship'], 'https://scholarships.gov.in/', 'current', now(), 'https://scholarships.gov.in/'),
('00000000-0000-0000-0000-000000000008', 'Pradhan Mantri MUDRA Yojana', 'Central Government', 'A Government of India credit programme for eligible non-corporate, non-farm small and micro enterprises through participating lenders.', 'Ministry of Finance', 'Entrepreneurship', 'Central', null, array['MUDRA credit products through participating lending institutions'], array['Eligible non-corporate, non-farm small or micro enterprise conditions apply'], array['Lender-requested identity, business and financial documents'], 'https://www.mudra.org.in/', 'current', now(), 'https://www.mudra.org.in/'),
('00000000-0000-0000-0000-000000000009', 'PM Surya Ghar: Muft Bijli Yojana', 'Central Government', 'A Government of India rooftop solar programme for eligible residential electricity consumers under the notified scheme guidelines.', 'Ministry of New and Renewable Energy', 'Energy', 'Central', null, array['Rooftop solar support according to the applicable central financial assistance and scheme rules'], array['Residential electricity consumer and installation conditions apply'], array['Electricity connection, identity and vendor or installation documents as required'], 'https://pmsuryaghar.gov.in/', 'current', now(), 'https://pmsuryaghar.gov.in/'),
('00000000-0000-0000-0000-000000000010', 'Sukanya Samriddhi Account', 'Central Government', 'A Government-backed small-savings account for the benefit of a girl child, available through authorised channels under the applicable rules.', 'Ministry of Finance / Department of Economic Affairs', 'Women & Child', 'Central', null, array['Government-backed savings account interest and tax treatment according to prevailing rules'], array['Account eligibility and age conditions for the girl child apply'], array['Birth and guardian identity documents as required by the authorised channel'], 'https://www.indiapost.gov.in/Financial/pages/content/sukanya-samriddhi-account.aspx', 'current', now(), 'https://www.indiapost.gov.in/Financial/pages/content/sukanya-samriddhi-account.aspx')
on conflict (id) do update set
  name = excluded.name, scheme_type = excluded.scheme_type, description = excluded.description, ministry = excluded.ministry,
  category = excluded.category, level = excluded.level, state = excluded.state, benefits = excluded.benefits,
  eligibility = excluded.eligibility, documents_required = excluded.documents_required, application_url = excluded.application_url,
  status = excluded.status, last_verified_at = excluded.last_verified_at, source_url = excluded.source_url, updated_at = now();
